export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';
export const PROCESS_USER_AUTHENTICATION = 'PROCESS_USER_AUTHENTICATION';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const IS_LOADING = 'IS_LOADING';
export const DOWNLOAD_FACTIONS = 'DOWNLOAD_FACTIONS';
export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const PROCESS_USER = 'PROCESS_USER';
// Factions
export const LOAD_FACTIONS = 'LOAD_FACTIONS';
export const CREATE_FACTION = 'CREATE_FACTION';
export const EDIT_FACTION = 'EDIT_FACTION';
