export default [
  {
    faction: 'Biochrondys',
    logo: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Logos/Biochrondys.png',
    augments: [
      {
        id: 'cb979420-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Mutation',
        name: 'Retractable Claws',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/RetractableClaws.png',
        action: 'Passive',
        desc: 'Doesn\'t fall when finishing move on a wall.',
      },
      {
        id: 'cffd4910-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Mutation',
        name: 'Modified Muscle',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/ModifiedMuscle.png',
        action: 'Tap',
        desc: 'Take an extra action.',
      },
      {
        id: 'dd00cdbc-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Mutation',
        name: 'Refractive Tissue',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/RefractiveTissue.png',
        action: 'Tap',
        desc: 'Cannot be attacked until you untap or take an action.',
      },
    ],
  },
  {
    faction: 'Gatekeepers',
    logo: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Logos/Gatekeepers.png',
    augments: [
      {
        id: '244b8fae-c795-11e9-aa8c-2a2ae2dbcce4',
        type: 'Tactics',
        name: 'Decisive Action',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/DecisiveAction.png',
        action: 'Tap',
        desc: 'Move twice speed.',
      },
      {
        id: '2a26e004-c795-11e9-aa8c-2a2ae2dbcce4',
        type: 'Tactics',
        name: 'Full Assault',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/FullAssault.png',
        action: 'Tap',
        desc: 'Double attack.',
      },
      {
        id: '3016d5dc-c795-11e9-aa8c-2a2ae2dbcce4',
        type: 'Tactics',
        name: 'Mimic Manoeuvre',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/MimicManoeuvre.png',
        action: 'Tap',
        desc: 'For one turn only, you can mimic another playing monster ability or augment.',
      },
    ],
  },
  {
    faction: 'Mechanica',
    logo: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Logos/Mechanica.png',
    augments: [
      {
        id: 'b660b708-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Cybernetics',
        name: 'Extra Limbs',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/ExtraLimbs.png',
        action: 'Tap',
        desc: 'Take an extra attack or move.',
      },
      {
        id: 'bb6ecdc0-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Cybernetics',
        name: 'Subdermal Plating',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/SubdermalPlating.png',
        action: 'Passive',
        desc: 'Begin all games with double health',
      },
      {
        id: 'be6cf54c-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Cybernetics',
        name: 'Nanorepair Module',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/NanorepairModule.png',
        action: 'Passive',
        desc: 'Regains One health point',
      },
    ],
  },
  {
    faction: 'Voidborn',
    logo: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Logos/Voidborn.png',
    augments: [
      {
        id: 'e1dd3dac-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Lens',
        name: 'Unphase',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/Unphase.png',
        action: 'Tap',
        desc: 'Teleport to anywhere on the map. Monsters cannot attack immediately after use.',
      },
      {
        id: 'e823d3f6-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Lens',
        name: 'Gravitybend',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/GravityBend.png',
        action: 'Tap',
        desc: 'All monsters must move a direction of your choice until they hit an object on the map.',
      },
      {
        id: 'eb393374-c794-11e9-aa8c-2a2ae2dbcce4',
        type: 'Lens',
        name: 'Reversion',
        image: 'https://hmg-images-capstone2019.s3-ap-southeast-2.amazonaws.com/Augments/Reversion.png',
        action: 'Tap',
        desc: 'Returns monster to location before their last move.',
      },
    ],
  },
];
