export default [
  {
    faction: 'Biochrondys',
    beasts: [
      {
        id: '33525fde-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Carnosaur',
        desc: 'Agile Predator',
        image: '',
        move: 'Jumps from rooftop to rooftop',
        damage: '1',
        maxdmg: '5',
        leap: '2',
        maxleap: '6',
        hp: '1',
        maxhp: '5',
        speed: '3',
        maxspeed: '7',
      },
      {
        id: '3b25a1da-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Abyssate',
        desc: 'Leaping Carnivore',
        image: '',
        move: 'Moves instantly from ground to rooftops',
        damage: '2',
        maxdmg: '6',
        leap: '3',
        maxleap: '7',
        hp: '2',
        maxhp: '6',
        speed: '4',
        maxspeed: '8',
      },
      {
        id: '416453ac-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Vaulterix',
        desc: 'Apex Draconian',
        image: '',
        move: 'Fly&#39s in any direction at any time.',
        damage: '3',
        maxdmg: '7',
        leap: '0',
        maxleap: '0',
        hp: '3',
        maxhp: '7',
        speed: '5',
        maxspeed: '9',
      },
    ],
  },
  {
    faction: 'Gatekeeper',
    beasts: [
      {
        id: '529d4e12-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Infiltrators',
        desc: 'Hunt and Track (Unit of 4)',
        image: '',
        move:
          'Each turn, one unit can zipline to any surface in line of sight.',
        damage: '1',
        maxdmg: '5',
        leap: '1',
        maxleap: '5',
        hp: '1',
        maxhp: '0',
        speed: '2',
        maxspeed: '0',
      },
      {
        id: '5828cc30-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Containment',
        desc: 'Search and Capture (Unit of 4)',
        image: '',
        move: 'Runs along walls.',
        damage: '1',
        maxdmg: '5',
        leap: '2',
        maxleap: '6',
        hp: '2',
        maxhp: '0',
        speed: '3',
        maxspeed: '0',
      },
      {
        id: '5d7322bc-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Tactical Team',
        desc: 'Seek and Destroy (Unit of 4)',
        image: '',
        move: 'Can move down streets through the air as movement.',
        damage: '1',
        maxdmg: '5',
        leap: '3',
        maxleap: '7',
        hp: '3',
        maxhp: '0',
        speed: '4',
        maxspeed: '0',
      },
    ],
  },
  {
    faction: 'Mechanica',
    beasts: [
      {
        id: '659051d6-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Clamberer',
        desc: 'Four-Armed Automation',
        image: 'clamberer.png',
        move: 'Climbs the sides of buildings.',
        damage: '2',
        maxdmg: '6',
        leap: '1',
        maxleap: '5',
        hp: '2',
        maxhp: '6',
        speed: '2',
        maxspeed: '6',
      },
      {
        id: '6ddff83c-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Bastion',
        desc: 'Armoured Hulk',
        image: '',
        move: 'Smashes through walls.',
        damage: '3',
        maxdmg: '7',
        leap: '1',
        maxleap: '5',
        hp: '3',
        maxhp: '7',
        speed: '2',
        maxspeed: '6',
      },
      {
        id: '76d7d3f6-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Subterrak',
        desc: 'Tunneling Behemoth',
        image: '',
        move: 'Dissapear underground.\nDisappear overground.',
        damage: '4',
        maxdmg: '8',
        leap: '1',
        maxleap: '5',
        hp: '4',
        maxhp: '12',
        speed: '2',
        maxspeed: '6',
      },
    ],
  },
  {
    faction: 'Voidborn',
    beasts: [
      {
        id: '8044570c-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Axial Beast',
        desc: 'Phase Creature',
        image: '',
        move: 'Phases through walls.',
        damage: '2',
        maxdmg: '6',
        leap: '1',
        maxleap: '5',
        hp: '1',
        maxhp: '5',
        speed: '2',
        maxspeed: '6',
      },
      {
        id: '85eacf60-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Node Horror',
        desc: 'Transdimensional Hunter',
        image: '',
        move: 'Phases from one wall to any other wall on the map.',
        damage: '3',
        maxdmg: '7',
        leap: '1',
        maxleap: '5',
        hp: '2',
        maxhp: '6',
        speed: '2',
        maxspeed: '6',
      },
      {
        id: '912e1706-c793-11e9-aa8c-2a2ae2dbcce4',
        name: 'Nexus Hivemind',
        desc: 'Ominscient Horror',
        image: '',
        move: 'Teleports to any point on the map.',
        damage: '4',
        maxdmg: '8',
        leap: '1',
        maxleap: '5',
        hp: '3',
        maxhp: '7',
        speed: '1',
        maxspeed: '5',
      },
    ],
  },
];
