import React, { Component } from 'react';

class Game extends Component {
    render() {
        return(<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem dolor, commodo ac sem eu, luctus congue nulla. Sed molestie tempus ullamcorper. Maecenas faucibus fermentum massa, quis condimentum sapien. Nullam sagittis, massa id feugiat gravida, felis nibh tincidunt ante, nec pellentesque arcu arcu fringilla quam. Etiam rhoncus rhoncus nunc. Curabitur lacus felis, rutrum ut elementum sit amet, tempus nec velit. Praesent mattis massa vitae justo faucibus vulputate. Nulla facilisi. Nam bibendum, orci in consectetur laoreet, ipsum quam vestibulum tellus, ut semper purus purus a mi. Donec consectetur mi sed orci porttitor, eu aliquam ante fermentum. Sed non magna vel diam fermentum aliquam.

            Maecenas malesuada turpis sit amet nunc pellentesque efficitur. Vivamus ante diam, sodales et ornare congue, viverra euismod ligula. Nunc quis quam ut nibh feugiat gravida. Duis consequat tellus a mollis dignissim. Aliquam tincidunt massa nec massa euismod luctus. Sed eu ullamcorper massa. Morbi nunc urna, feugiat vitae lectus in, varius porttitor sapien. Suspendisse nec dolor id nulla efficitur rhoncus sed eget arcu. Phasellus fringilla, turpis vel dignissim sodales, risus nisi semper sem, id molestie magna lacus viverra purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus sit amet urna commodo, pharetra sapien ut, convallis turpis. Vivamus fringilla varius fringilla.
            
            Proin id accumsan enim. Etiam rutrum nulla quam, a ornare risus tincidunt eu. Vivamus quis bibendum metus, sit amet tristique augue. Vestibulum egestas sodales lacus, id mollis dolor gravida in. Quisque at vestibulum orci. In hac habitasse platea dictumst. Cras rhoncus sem ut odio tincidunt, vitae dignissim ante luctus. Suspendisse ligula diam, ultricies in turpis ac, bibendum placerat risus. Integer ornare vulputate augue, a sodales odio blandit eu. Duis non consequat velit. Suspendisse massa augue, semper at nisl ac, laoreet suscipit turpis. Nam blandit ullamcorper nisl, ut sollicitudin dolor commodo at. Phasellus pharetra, diam vel laoreet mollis, diam odio ultrices leo, quis condimentum quam tellus sed felis.
            
            Aliquam rutrum venenatis lectus vitae efficitur. Vestibulum eget mauris enim. Maecenas et lectus laoreet, ultricies mi vel, pulvinar ex. Suspendisse ac laoreet libero. Etiam malesuada auctor vehicula. Fusce rhoncus, lorem id bibendum sollicitudin, enim neque egestas eros, ac egestas massa mi a justo. Nulla nibh nunc, egestas at nunc a, pharetra ullamcorper felis.
            
            Proin aliquam consequat diam vel porttitor. Nulla odio elit, convallis nec felis quis, dictum consectetur augue. Nam eget turpis tristique, vulputate sem non, bibendum nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin molestie enim vel magna bibendum tempor. Sed consectetur eget dolor nec rutrum. Morbi blandit leo a risus pretium, sed laoreet est varius. Proin volutpat aliquet massa, vel dignissim mauris volutpat ut. Mauris commodo nisi semper, ullamcorper dolor a, suscipit magna. Fusce et porttitor libero. Fusce nec dapibus diam, quis ullamcorper nibh. Donec interdum justo eget eleifend interdum. Sed fringilla pretium pharetra. Donec luctus, tellus in rhoncus convallis, quam urna iaculis ipsum, congue auctor urna risus at augue. Cras rutrum justo et vulputate dignissim.</div>);
    }
}

export default Game;